exec-once = [workspace name:code silent] $terminal
exec-once = [silent] steam -silent
exec-once = [workspace 1 silent] flatpak run com.discordapp.Discord
exec-once = [workspace special:mail silent] flatpak run org.mozilla.Thunderbird
exec-once = [workspace special:browser silent] qutebrowser

exec-once = fcitx5
exec-once = udiskie
exec-once = swaync
exec-once = hyprpaper
exec-once = waybar
exec-once = hyprpolkitagent
exec-once = vicinae server
